[workspace]
members = [
    "crates/lianyaohu-app",
    "crates/lianyaohu-core",
]
default-members = [
    "crates/lianyaohu-app",
    "crates/lianyaohu-core",
]
resolver = "3"

[workspace.package]
authors = ["Max Lv"]
edition = "2024"
homepage = "https://lyh.maxlv.net"
license = "MIT"
readme = "README.md"
repository = "https://github.com/madeye/LianYaoHu"
version = "0.2.0"

[workspace.dependencies]
lianyaohu-core = { path = "crates/lianyaohu-core", version = "0.2.0" }
libc = "0.2"
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
toml = "0.9"
